# Configure basic settings for JupyterHub
# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html
# https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html
# https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html
proxy:
  secretToken: "<RANDOM_HEX>"
singleuser:
  image:
    name: dkharazi/anf-docker
    tag: latest
