# Configure basic settings for JupyterHub
# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html
# https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html
# https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html
proxy:
  secretToken: "<RANDOM_HEX>"
singleuser:
  image:
    name: anfpy
    tag: 1.0.0
imagePullPolicy: Never
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: true
